name: Backend CI logic

on:
  workflow_call: # This allows other workflows to "call" this one

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore .Net tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore backend.sln

      - name: Check formatting
        run: dotnet csharpier check .

      - name: Build
        run: dotnet build backend.sln --no-restore

      - name: Test
        run: dotnet test backend.sln --no-build --verbosity normal
