name: Deploy to production

concurrency:
  group: production-deployment
  cancel-in-progress: false # Set to false so we don't interrupt a Docker build mid-way

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "Specific commit hash to deploy (leave blank for latest)"
        required: false
        type: string

jobs:
  frontend-ci:
    uses: ./.github/workflows/frontend-ci.yml

  backend-ci:
    uses: ./.github/workflows/_backend-ci.yml

  deploy:
    needs: [frontend-ci, backend-ci]
    runs-on: self-hosted
    steps:
      - name: Pull code
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.commit_hash || github.sha }}

      - name: Set up environment
        run: |
          cp ~/env/backend.env ./backend/.env
          cp ~/env/frontend.env ./frontend/.env

      - name: Deploy
        env:
          BACKEND_CONTAINER_NAME: healthtech-backend
          FRONTEND_CONTAINER_NAME: healthtech-frontend
          TRAEFIK_CONTAINER_NAME: healthtech-traefik
          DB_CONTAINER_NAME: healthtech-db
        run: |
          echo "Rebuilding and deploying..."
          docker compose --env-file ./backend/.env -f docker-compose.prod.yml up --build -d

          # Simple health check
          sleep 15
          if [ "$(docker inspect -f '{{.State.Running}}' ${DB_CONTAINER_NAME})" == "false" ]; then
              echo "Database failed to start after 15s. Printing logs:"
              docker logs ${DB_CONTAINER_NAME} | tail -n 20 
              exit 1
          fi
          if [ "$(docker inspect -f '{{.State.Running}}' ${BACKEND_CONTAINER_NAME})" == "false" ]; then
              echo "Backend failed to start after 15s. Printing logs:"
              docker logs ${BACKEND_CONTAINER_NAME} | tail -n 20 
              exit 1
          fi
          if [ "$(docker inspect -f '{{.State.Running}}' ${FRONTEND_CONTAINER_NAME})" == "false" ]; then
              echo "Frontend failed to start after 15s. Printing logs:"
              docker logs ${FRONTEND_CONTAINER_NAME} | tail -n 20 
              exit 1
          fi
          if [ "$(docker inspect -f '{{.State.Running}}' ${TRAEFIK_CONTAINER_NAME})" == "false" ]; then
              echo "Traefik failed to start after 15s. Printing logs:"
              docker logs ${TRAEFIK_CONTAINER_NAME} | tail -n 20 
              exit 1
          fi

          echo "Deployment successful. Cleaning up old images..."
          docker image prune -f
